# Generated by Django 4.0 on 2022-03-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avater',
            field=models.ImageField(default='avater.jpg', null=True, upload_to='user/avater'),
        ),
    ]
